server:
  port: 9092

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yungo?characterEncoding=utf8
    username: root
    password: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 50
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

my:
  chuanglan:
    account:
    password: